image: python:3.10

pipelines:
  tags:
    '*[0-9].*[0-9].*[0-9]':
    - step:
        oidc: true
        name: Upload Image Vulnerability Scan Report
        caches:
          - pip
        script:
          - export IMAGE_TAG=${BITBUCKET_TAG}
          - export AWS_REGION=$AWS_DEFAULT_REGION
          - export REGISTRY_ID=$REGISTRY_ID
          - apt-get update && apt-get install -y awscli &&  apt-get install -y jq
          - assume_role_response=$(aws sts assume-role-with-web-identity --role-arn $AWS_ROLE_ARN --role-session-name build-session  --web-identity-token "$BITBUCKET_STEP_OIDC_TOKEN" --duration-seconds 1000)
          - access_key_id=$(echo "$assume_role_response" | jq '.Credentials.AccessKeyId' |tr -d '"')
          - secret_access_key=$(echo "$assume_role_response" | jq '.Credentials.SecretAccessKey' |tr -d '"')
          - session_token=$(echo "$assume_role_response" | jq '.Credentials.SessionToken' |tr -d '"')
          - export AWS_ACCESS_KEY_ID=$access_key_id
          - export AWS_SECRET_ACCESS_KEY=$secret_access_key
          - export AWS_SESSION_TOKEN=$session_token
          - pip3 install pandas openpyxl pyyaml
          - python3 ECR-image-scan-script.py

          # Use the captured filename with the atlassian/bitbucket-upload-file pipe
          - pipe: atlassian/bitbucket-upload-file:0.6.0
            variables:
              BITBUCKET_USERNAME: $BITBUCKET_UPLOAD_USERNAME
              BITBUCKET_APP_PASSWORD: $BITBUCKET_UPLOAD_PASSWORD
              FILENAME: ${IMAGE_TAG}.xlsx





